import json
import asyncio
from pathlib import Path
from infrastructure.content.json_content_loader import JsonContentLoader

# Existing 20 words to preserve exactly
EXISTING_WORDS = [
    {
        "id": "vocab_001",
        "word": "abundant",
        "translation": "plentiful",
        "transcription": "/əˈbʌndənt/",
        "example": "The region has abundant natural resources.",
        "level": "B2"
    },
    {
        "id": "vocab_002",
        "word": "acquire",
        "translation": "to obtain or gain",
        "transcription": "/əˈkwaɪər/",
        "example": "Students acquire new vocabulary through repeated practice.",
        "level": "B1"
    },
    {
        "id": "vocab_003",
        "word": "adapt",
        "translation": "to adjust to new conditions",
        "transcription": "/əˈdæpt/",
        "example": "Animals must adapt to changes in their environment.",
        "level": "B1"
    },
    {
        "id": "vocab_004",
        "word": "adequate",
        "translation": "sufficient",
        "transcription": "/ˈædəkwət/",
        "example": "The study provided adequate evidence for the theory.",
        "level": "B2"
    },
    {
        "id": "vocab_005",
        "word": "advocate",
        "translation": "to publicly support",
        "transcription": "/ˈædvəkeɪt/",
        "example": "Many scientists advocate stronger climate policies.",
        "level": "C1"
    },
    {
        "id": "vocab_006",
        "word": "allocate",
        "translation": "to distribute for a purpose",
        "transcription": "/ˈæləkeɪt/",
        "example": "The university will allocate more funds to research.",
        "level": "C1"
    },
    {
        "id": "vocab_007",
        "word": "ambiguous",
        "translation": "unclear or having multiple meanings",
        "transcription": "/æmˈbɪɡjuəs/",
        "example": "The instructions were ambiguous and confused many students.",
        "level": "C1"
    },
    {
        "id": "vocab_008",
        "word": "analyze",
        "translation": "to examine carefully",
        "transcription": "/ˈænəlaɪz/",
        "example": "Researchers analyze data before drawing conclusions.",
        "level": "B1"
    },
    {
        "id": "vocab_009",
        "word": "apparent",
        "translation": "clearly visible or understood",
        "transcription": "/əˈpærənt/",
        "example": "It became apparent that the experiment had failed.",
        "level": "B2"
    },
    {
        "id": "vocab_010",
        "word": "approach",
        "translation": "a method or way of doing something",
        "transcription": "/əˈproʊtʃ/",
        "example": "The professor used a new approach to teaching grammar.",
        "level": "B1"
    },
    {
        "id": "vocab_011",
        "word": "assess",
        "translation": "to evaluate",
        "transcription": "/əˈsɛs/",
        "example": "The test is designed to assess academic reading skills.",
        "level": "B2"
    },
    {
        "id": "vocab_012",
        "word": "beneficial",
        "translation": "helpful or useful",
        "transcription": "/ˌbɛnəˈfɪʃəl/",
        "example": "Regular review is beneficial for long-term memory.",
        "level": "B2"
    },
    {
        "id": "vocab_013",
        "word": "coherent",
        "translation": "clear and logically connected",
        "transcription": "/koʊˈhɪrənt/",
        "example": "A strong essay needs a coherent argument.",
        "level": "C1"
    },
    {
        "id": "vocab_014",
        "word": "derive",
        "translation": "to come from a source",
        "transcription": "/dɪˈraɪv/",
        "example": "Many English words derive from Latin.",
        "level": "B2"
    },
    {
        "id": "vocab_015",
        "word": "distinct",
        "translation": "clearly different",
        "transcription": "/dɪˈstɪŋkt/",
        "example": "The two theories have distinct explanations.",
        "level": "B2"
    },
    {
        "id": "vocab_016",
        "word": "emerge",
        "translation": "to appear or become known",
        "transcription": "/iˈmərdʒ/",
        "example": "New problems may emerge during the research process.",
        "level": "B2"
    },
    {
        "id": "vocab_017",
        "word": "emphasize",
        "translation": "to give special importance to",
        "transcription": "/ˈɛmfəsaɪz/",
        "example": "TOEFL teachers emphasize clear organization in writing.",
        "level": "B1"
    },
    {
        "id": "vocab_018",
        "word": "evidence",
        "translation": "facts that support an idea",
        "transcription": "/ˈɛvɪdəns/",
        "example": "The author presents evidence to support the claim.",
        "level": "B1"
    },
    {
        "id": "vocab_019",
        "word": "imply",
        "translation": "to suggest without saying directly",
        "transcription": "/ɪmˈplaɪ/",
        "example": "The passage implies that the policy was unpopular.",
        "level": "B2"
    },
    {
        "id": "vocab_020",
        "word": "significant",
        "translation": "important or meaningful",
        "transcription": "/sɪɡˈnɪfɪkənt/",
        "example": "The discovery had a significant impact on medicine.",
        "level": "B1"
    }
]

# Raw content database of 280 TOEFL words (grouped by B2/C1, academic topics)
NEW_WORDS_RAW = [
    # --- SCIENCE & BIOLOGY ---
    ("hypothesis", "a proposed explanation based on limited evidence", "/haɪˈpɑːθəsɪs/", "The researchers formulated a hypothesis about the chemical reaction.", "C1"),
    ("empirical", "based on observation or experiment rather than theory", "/ɛmˈpɪrɪkəl/", "We need empirical evidence to validate this claim.", "C1"),
    ("synthesis", "the combination of ideas to form a theory or system", "/ˈsɪnθəsɪs/", "The essay is a synthesis of several historical accounts.", "C1"),
    ("catalyst", "a substance that increases the rate of a chemical reaction", "/ˈkætəlɪst/", "Enzymes act as a catalyst in metabolic processes.", "B2"),
    ("equilibrium", "a state of physical balance or stability", "/ˌikwɪˈlɪbriəm/", "The ecosystem reached a stable equilibrium after many years.", "C1"),
    ("symbiosis", "interaction between two different organisms living in close association", "/sɪmbaɪˈoʊsɪs/", "Lichens are a classic example of symbiosis.", "C1"),
    ("mutation", "a change in the genetic structure of an organism", "/mjuˈteɪʃən/", "Some genetic mutations are beneficial for survival.", "B2"),
    ("respiration", "the act of breathing; cell energy generation", "/ˌrɛspəˈreɪʃən/", "Aerobic respiration requires a continuous supply of oxygen.", "B2"),
    ("velocity", "the speed of something in a given direction", "/vəˈlɑːsəti/", "The object's velocity increased as it rolled down the hill.", "B2"),
    ("diffusion", "the spreading of something more widely", "/dɪˈfjuːʒən/", "The diffusion of gases occurs rapidly in warm temperatures.", "B2"),
    ("acceleration", "the rate of change of velocity per unit of time", "/ækˌsɛləˈreɪʃən/", "The car had rapid acceleration on the straight track.", "B2"),
    ("friction", "the resistance encountered when moving over another surface", "/ˈfrɪkʃən/", "Rough surfaces produce more friction than smooth ones.", "B2"),
    ("conduction", "the transfer of heat or electricity through a substance", "/kənˈdʌkʃən/", "Metal is an excellent material for thermal conduction.", "B2"),
    ("radiation", "the emission of energy as electromagnetic waves", "/ˌreɪdiˈeɪʃən/", "The earth receives solar radiation from the sun.", "B2"),
    ("convection", "heat transfer by the movement of fluid or gas", "/kənˈvɛkʃən/", "Warm air rises due to the process of convection.", "B2"),
    ("nucleus", "the central and most important part of an object or cell", "/ˈnuːkliəs/", "Most of the cell's genetic material is in the nucleus.", "B2"),
    ("physiological", "relating to the normal functioning of a living organism", "/ˌfɪziəˈlɑːdʒɪkəl/", "Extreme cold triggers several physiological responses.", "C1"),
    ("anatomical", "relating to bodily structure or anatomy", "/ˌænəˈtɑːmɪkəl/", "There are key anatomical differences between birds and bats.", "C1"),
    ("secretion", "the process of releasing a substance from a gland or cell", "/sɪˈkriːʃən/", "Saliva is a vital secretion for food digestion.", "C1"),
    ("pathogen", "a bacterium, virus, or microorganism that causes disease", "/ˈpæθədʒən/", "The immune system defends the body against pathogens.", "C1"),
    ("specimen", "an individual animal, plant, or piece of mineral used as an example", "/ˈspɛsəmən/", "Botanists collected specimens of rare ferns in the rainforest.", "B2"),
    ("osmosis", "the movement of water molecules through a membrane", "/ɑːzˈmoʊsɪs/", "Plants absorb water from the soil through osmosis.", "C1"),
    ("photosynthesis", "the process by which green plants make food from sunlight", "/ˌfoʊtoʊˈsɪnθəsɪs/", "Chlorophyll is essential for photosynthesis.", "B2"),
    ("organism", "an individual animal, plant, or single-celled life form", "/ˈɔːrɡənˌɪzəm/", "Bacteria are microscopic organisms found everywhere.", "B2"),
    ("metabolism", "the chemical processes that occur within a living organism", "/məˈtæbəlɪzəm/", "A fast metabolism helps convert food into energy quickly.", "B2"),
    ("cellular", "relating to or consisting of cells", "/ˈsɛljələr/", "Cellular respiration occurs in the mitochondria.", "B2"),
    ("evolutionary", "relating to the gradual development of something", "/ˌɛvəˈluːʃənɛri/", "Flight was a major evolutionary advantage for birds.", "C1"),
    ("genetics", "the study of heredity and inherited characteristics", "/dʒɛˈnɛtɪks/", "Modern genetics can identify predispositions to diseases.", "B2"),
    ("ecosystem", "a biological community of interacting organisms", "/ˈikoʊˌsɪstəm/", "Coral reefs support a highly diverse marine ecosystem.", "B2"),
    ("biodiversity", "the variety of plant and animal life in a habitat", "/ˌbaɪoʊdaɪˈvərsəti/", "Deforestation leads to a severe loss of biodiversity.", "B2"),
    ("classification", "the action or process of classifying something", "/ˌklæsɪfɪˈkeɪʃən/", "The classification of minerals is based on chemical composition.", "B2"),
    ("resilience", "the capacity to recover quickly from difficulties", "/rɪˈzɪliəns/", "The ecosystem showed great resilience after the wildfire.", "C1"),
    ("reproduce", "to produce offspring or make a copy", "/ˌriprəˈdus/", "Mammals reproduce sexually and nurture their young.", "B2"),
    ("thermodynamics", "the branch of physics dealing with heat and energy relations", "/ˌθərmoʊdaɪˈnæmɪks/", "The laws of thermodynamics govern chemical reactions.", "C1"),
    ("entropy", "a measure of disorder or randomness in a system", "/ˈɛntrəpi/", "Systems naturally progress from order to higher entropy.", "C1"),
    ("velocity", "speed in a given direction", "/vəˈlɑːsəti/", "The escape velocity of Earth is about 11.2 kilometers per second.", "B2"),
    ("amplitude", "the maximum extent of a vibration or oscillation", "/ˈæmplɪtud/", "The amplitude of the sound wave determines its loudness.", "C1"),
    ("resonance", "the reinforcement or prolongation of sound by reflection", "/ˈrɛzənəns/", "The acoustic resonance of the hall enhanced the music.", "C1"),
    ("catalysis", "the acceleration of a chemical reaction by a catalyst", "/kəˈtæləsɪs/", "Industrial processes rely on catalysis to save energy.", "C1"),
    ("synthetic", "made by chemical synthesis, especially to imitate a natural product", "/sɪnˈθɛtɪk/", "Synthetic fibers are often stronger than natural cotton.", "B2"),
    ("secretion", "the generation and release of a chemical by a cell", "/sɪˈkriːʃən/", "Hormone secretion is regulated by feedback loops.", "C1"),
    ("enzyme", "a substance produced by a living organism acting as a catalyst", "/ˈɛnzaɪm/", "Digestive enzymes break down complex food molecules.", "B2"),
    ("biodegradation", "decomposition of organic substances by microorganisms", "/ˌbaɪoʊˌdɛɡrəˈdeɪʃən/", "Plastic bags resist biodegradation for hundreds of years.", "C1"),
    ("pathogenic", "capable of causing disease", "/pæθəˈdʒɛnɪk/", "Most bacteria are harmless, but pathogenic strains exist.", "C1"),
    ("anatomy", "the branch of science concerned with bodily structure", "/əˈnætəmi/", "Students of medicine study human anatomy in detail.", "B2"),
    ("adaptation", "the action or process of adapting to an environment", "/ˌædəpˈteɪʃən/", "Cacti have adaptations that allow them to store water.", "B2"),
    ("biome", "a large community of flora and fauna occupying a major habitat", "/ˈbaɪoʊm/", "The tundra biome is characterized by freezing temperatures.", "B2"),
    ("geological", "relating to the study of the earth's physical structure", "/ˌdʒiəˈlɑːdʒɪkəl/", "Geological shifts created the mountain range millions of years ago.", "B2"),
    ("sediment", "matter that settles to the bottom of a liquid", "/ˈsɛdɪmənt/", "Rivers carry sediment that deposits at the ocean mouth.", "B2"),
    ("erosion", "the process of eroding or being eroded by wind or water", "/ɪˈroʊʒən/", "Plant roots protect the hillside soil from erosion.", "B2"),

    # --- ENVIRONMENT ---
    ("sustainability", "the ability to be maintained at a certain rate or level", "/səˌsteɪnəˈbɪlɪti/", "Renewable energy is crucial for long-term sustainability.", "B2"),
    ("conservation", "the action of conserving something, especially the environment", "/ˌkɑːnsərˈveɪʃən/", "Wildlife conservation programs protect endangered species.", "B2"),
    ("deforestation", "the clearing of forest lands", "/ˌdifɔːrəˈsteɪʃən/", "Deforestation destroys the natural habitats of millions of animals.", "B2"),
    ("precipitation", "rain, snow, sleet, or hail that falls to the ground", "/prɪˌsɪpɪˈteɪʃən/", "The desert receive very little annual precipitation.", "B2"),
    ("meteorological", "relating to the atmosphere and weather phenomena", "/ˌmiːtiərəˈlɑːdʒɪkəl/", "Meteorological satellites track major hurricane movements.", "C1"),
    ("desertification", "the process by which fertile land becomes desert", "/dɪˌzərtɪfɪˈkeɪʃən/", "Overgrazing is a primary cause of desertification in Africa.", "C1"),
    ("salinity", "the concentration of dissolved salts in water", "/səˈlɪnɪti/", "High salinity levels make it difficult for freshwater fish to survive.", "C1"),
    ("contamination", "the action of making something impure or polluted", "/kənˌtæmɪˈneɪʃən/", "Chemical runoff led to the contamination of the drinking water.", "B2"),
    ("reclamation", "the act of returning land to a useful or natural state", "/ˌrɛkləˈmeɪʃən/", "The city began a land reclamation project along the coast.", "C1"),
    ("afforestation", "the establishment of a forest in an area where there was none", "/əˌfɔːrəˈsteɪʃən/", "Afforestation projects help absorb carbon dioxide from the air.", "C1"),
    ("aquifer", "a body of permeable rock containing groundwater", "/ˈækwɪfər/", "The region relies on a deep aquifer for agricultural irrigation.", "C1"),
    ("atmosphere", "the envelope of gases surrounding the earth or another planet", "/ˈætməsˌfɪr/", "Pollutants in the atmosphere can trap heat and raise temperatures.", "B2"),
    ("biosphere", "the regions of the surface, atmosphere, and hydrosphere of the earth occupied by living organisms", "/ˈbaɪoʊˌsfɪr/", "All life exists within the thin layer of the biosphere.", "B2"),
    ("ecology", "the relation of organisms to one another and to their physical surroundings", "/ɪˈkɑːlədʒi/", "Human activities have disrupted the delicate ecology of the lake.", "B2"),
    ("emissions", "the production and discharge of something, especially gas or radiation", "/iˈmɪʃənz/", "Governments aim to reduce greenhouse gas emissions by 2030.", "B2"),
    ("estuary", "the tidal mouth of a large river, where the tide meets the stream", "/ˈɛstjʊri/", "The estuary is a rich nursery ground for young fish and crabs.", "C1"),
    ("habitat", "the natural home or environment of an animal, plant, or other organism", "/ˈhæbɪtæt/", "Wetlands provide a crucial habitat for migrating waterfowl.", "B2"),
    ("hydrology", "the branch of science concerned with the properties of the earth's water", "/haɪˈdrɑlədʒi/", "Deforestation significantly alters the local hydrology of a valley.", "C1"),
    ("precipitation", "weather precipitation, like rain or snow", "/prɪˌsɪpɪˈteɪʃən/", "Heavy precipitation caused flooding in low-lying residential areas.", "B2"),
    ("runoff", "the draining away of water from the surface of an area of land", "/ˈrʌnˌɑf/", "Agricultural runoff contains pesticides that harm aquatic ecosystems.", "B2"),
    ("temperate", "relating to a region or climate characterized by mild temperatures", "/ˈtɛmpərət/", "Deciduous forests grow mainly in the temperate zone.", "B2"),
    ("topography", "the arrangement of the natural and artificial physical features of an area", "/təˈpɑɡrəfi/", "The topography of the island is dominated by volcanic mountains.", "C1"),
    ("tributary", "a river or stream flowing into a larger river or lake", "/ˈtrɪbjʊtəri/", "The Ohio River is a major tributary of the Mississippi River.", "B2"),
    ("wetland", "land consisting of marshes or swamps; saturated land", "/ˈwɛtlænd/", "Wetlands act as natural filters that purify freshwater supplies.", "B2"),
    ("depletion", "reduction in the number or quantity of something", "/dɪˈpliʃən/", "Ozone depletion allows harmful ultraviolet rays to reach Earth.", "B2"),
    ("arid", "having little or no rain; too dry or barren to support vegetation", "/ˈærɪd/", "Most cacti thrive in arid environments where water is scarce.", "B2"),
    ("semi-arid", "characterized by light rainfall; semi-dry", "/ˌsɛmiˈærɪd/", "The semi-arid grasslands are suitable for sheep herding.", "B2"),
    ("glaciation", "the process, condition, or result of being covered by glaciers or ice sheets", "/ˌɡleɪsiˈeɪʃən/", "The landscape was carved by glaciation during the last Ice Age.", "C1"),
    ("indigenous", "originating or occurring naturally in a particular place; native", "/ɪnˈdɪdʒɪnəs/", "Kangaroo is an indigenous species of Australia.", "B2"),
    ("parasite", "an organism that lives in or on another organism and benefits by deriving nutrients at the host's expense", "/ˈpærəˌsaɪt/", "Fleas are common parasites that feed on dogs and cats.", "B2"),
    ("predator", "an animal that naturally preys on others", "/ˈprɛdətər/", "Lions are apex predators that hunt large herbivores.", "B2"),
    ("prey", "an animal that is hunted and killed by another for food", "/preɪ/", "Zebras are the primary prey of African lions.", "B2"),
    ("toxic", "poisonous or harmful", "/ˈtɑːksɪk/", "Industrial waste can contain toxic chemicals that leach into soil.", "B2"),
    ("pollutant", "a substance that pollutes something, especially water or the atmosphere", "/pəˈlutənt/", "Carbon monoxide is a dangerous gaseous pollutant.", "B2"),
    ("conserve", "protect something from harm or destruction", "/kənˈsərv/", "National parks help conserve natural geological formations.", "B2"),
    ("sustain", "strengthen or support physically or mentally; maintain", "/səˈsteɪn/", "The soil must have enough nutrients to sustain crops.", "B2"),
    ("biodegradable", "capable of being decomposed by bacteria or other living organisms", "/ˌbaɪoʊdɪˈɡreɪdəbəl/", "Paper plates are biodegradable, whereas plastic ones are not.", "B2"),
    ("fertilizer", "a chemical or natural substance added to soil or land to increase its fertility", "/ˈfɜːrtəlaɪzər/", "Nitrogen fertilizers boost crop yields but can pollute nearby rivers.", "B2"),
    ("greenhouse", "glass building for growing plants; warming effect", "/ˈɡrinˌhaʊs/", "Carbon dioxide is a major greenhouse gas that traps warmth.", "B2"),
    ("acidification", "the process of becoming acid or acidic", "/əˌsɪdɪfɪˈkeɪʃən/", "Ocean acidification harms coral reefs and shellfish shells.", "C1"),
    ("carbon", "the chemical element of atomic number 6", "/ˈkɑːrbən/", "Carbon emissions are a major driver of global climate change.", "B2"),
    ("degrade", "break down or deteriorate chemically or physically", "/dɪˈɡreɪd/", "Solar radiation can degrade plastics over long periods.", "B2"),
    ("contaminant", "a polluting substance that makes something impure", "/kənˈtamɪnənt/", "Lead is a toxic contaminant occasionally found in old water pipes.", "B2"),
    ("ecosystem", "a community of interacting organisms and their environment", "/ˈikoʊˌsɪstəm/", "Introducing invasive species can disrupt the local ecosystem.", "B2"),
    ("canopy", "the high, leafy part of a forest", "/ˈkænəpi/", "Most birds in the rainforest nest high in the forest canopy.", "B2"),
    ("organic", "relating to or derived from living matter", "/ɔːrˈɡænɪk/", "Decomposing organic matter enriches the soil with nutrients.", "B2"),
    ("sustainable", "able to be maintained at a certain level without depletion", "/səˈsteɪnəbəl/", "Sustainable logging practices ensure that forests replant trees.", "B2"),
    ("endangered", "at risk of extinction", "/ɪnˈdeɪndʒəd/", "Giant pandas are a famous example of an endangered species.", "B2"),
    ("extinct", "having no living members", "/ɛkˈstɪŋkt/", "Dinosaurs became extinct millions of years ago.", "B2"),
    ("fauna", "the animals of a particular region, habitat, or geological period", "/ˈfɔːnə/", "Australia is famous for its unique marsupial fauna.", "B2"),

    # --- TECHNOLOGY & ENGINEERING ---
    ("infrastructure", "the basic physical and organizational structures needed for society", "/ˈɪnfrəˌstrʌktʃər/", "The government invested heavily in public transit infrastructure.", "B2"),
    ("automation", "the use of automatic equipment in manufacturing or processes", "/ˌɔtəˈmeɪʃən/", "Factory automation has significantly reduced labor costs.", "B2"),
    ("cybernetics", "the science of communications and automatic control systems", "/ˌsaɪbərˈnɛtɪks/", "Cybernetics bridges the gap between biology and mechanical systems.", "C1"),
    ("nanotechnology", "technology deal with dimensions of less than 100 nanometers", "/ˌnænoʊtɛkˈnɑlədʒi/", "Nanotechnology enables the creation of incredibly small microchips.", "C1"),
    ("biotechnology", "the exploitation of biological processes for industrial purposes", "/ˌbaɪoʊtɛkˈnɑːlədʒi/", "Biotechnology is used to develop new vaccines and medicines.", "C1"),
    ("algorithm", "a process or set of rules to be followed in calculations", "/ˈælɡərɪðəm/", "The search engine uses a complex algorithm to rank webpages.", "B2"),
    ("encryption", "the process of converting information into code", "/ɪnˈkrɪpʃən/", "Encryption ensures that online bank transactions are secure.", "C1"),
    ("optimization", "the action of making the best or most effective use of a situation", "/ˌɑptəmaɪˈzeɪʃən/", "Route optimization helps delivery drivers save time and fuel.", "C1"),
    ("mechanism", "a system of parts working together in a machine; a process", "/ˈmɛkənɪzəm/", "Scientists studied the mechanism by which the virus spreads.", "B2"),
    ("efficiency", "the state or quality of being efficient; wasting minimal energy", "/ɪˈfɪʃənsi/", "The new hybrid engine operates with greater thermal efficiency.", "B2"),
    ("integration", "the action or process of combining structures into a whole", "/ɪntəˈɡreɪʃən/", "Software integration allows different apps to share data.", "B2"),
    ("simulation", "the imitation of the operation of a real-world process", "/ˌsɪmjʊˈleɪʃən/", "Pilots train in a flight simulation before flying real planes.", "B2"),
    ("robotics", "the branch of technology that deals with robots", "/roʊˈbɑːtɪks/", "Advanced robotics is changing the landscape of warehouse logistics.", "B2"),
    ("semiconductor", "a solid substance that has intermediate conductivity", "/ˌsɛmikənˈdʌktər/", "Silicon is the most widely used semiconductor in computer chips.", "C1"),
    ("transmission", "the action or process of transmitting something", "/trænzˈmɪʃən/", "High-voltage lines are used for electrical power transmission.", "B2"),
    ("protocol", "a system of rules explaining the correct procedure", "/ˈproʊtəˌkɑːl/", "The network protocol regulates how computers exchange files.", "B2"),
    ("wavelength", "the distance between successive crests of a wave", "/ˈweɪvˌlɛŋkθ/", "Blue light has a shorter wavelength than red light.", "B2"),
    ("frequency", "the rate at which something occurs or repeats", "/ˈfrikwənsi/", "Radio stations broadcast at a specific electromagnetic frequency.", "B2"),
    ("innovation", "the action or process of innovating; a new method or idea", "/ˌɪnəˈveɪʃən/", "Technological innovation drives economic growth and convenience.", "B2"),
    ("aerodynamics", "the study of the properties of moving air", "/ˌɛroʊdaɪˈnæmɪks/", "Car designers study aerodynamics to reduce wind resistance.", "C1"),
    ("combustion", "the process of burning something", "/kəmˈbʌstʃən/", "Internal combustion engines burn gasoline to generate power.", "B2"),
    ("conductivity", "the degree to which a material conducts electricity or heat", "/ˌkɑndʌkˈtɪvɪti/", "Copper is highly valued for its electrical conductivity.", "C1"),
    ("corrosion", "the process of corroding; chemical damage over time", "/kəˈroʊʒən/", "Rust is a common form of metal corrosion caused by moisture.", "C1"),
    ("prototype", "a first, typical or preliminary model of something", "/ˈproʊtətaɪp/", "Engineers built a prototype of the electric car for road testing.", "B2"),
    ("satellite", "an artificial body placed in orbit round the earth", "/ˈsætəlaɪt/", "Weather satellites capture images of storm clouds.", "B2"),
    ("synthetic", "made by chemical synthesis, especially to imitate a natural product", "/sɪnˈθɛtɪk/", "Synthetic materials are often used in sports gear for durability.", "B2"),
    ("telecommunications", "communication over a distance by cable, telegraph, or broadcasting", "/ˌtɛlɪkəˌmjunɪˈkeɪʃənz/", "Fiber-optic cables revolutionized the telecommunications industry.", "C1"),
    ("terminal", "a device at which a user enters data or commands; end point", "/ˈtərmɪnəl/", "Passengers boarded the bus at the central terminal.", "B2"),
    ("traction", "the action of drawing or pulling something over a surface", "/ˈtrækʃən/", "Tires need good tread to maintain traction on wet roads.", "B2"),
    ("transmitter", "a set of equipment used to generate and transmit electromagnetic waves", "/trænzˈmɪtər/", "The radio transmitter broadcasts signal across the valley.", "B2"),
    ("turbine", "a machine for producing continuous power using fluid or air", "/ˈtərbaɪn/", "Wind turbines convert wind energy into electricity.", "B2"),
    ("vacuum", "a space entirely devoid of matter", "/ˈvækjum/", "Light travels slightly faster in a vacuum than through air.", "B2"),
    ("valve", "a device for controlling the passage of fluid or air", "/ˈvælv/", "The plumber replaced a faulty water valve in the basement.", "B2"),
    ("voltage", "an electromotive force or potential difference", "/ˈvoʊltɪdʒ/", "Most household appliances operate at a voltage of 110 or 220.", "B2"),
    ("silicon", "the chemical element of atomic number 14", "/ˈsɪlɪkən/", "Silicon Valley is named after the material used in microchips.", "B2"),
    ("software", "the programs and other operating information used by a computer", "/ˈsɔːftˌwɛr/", "Updating your software protects your computer from viruses.", "B2"),
    ("hardware", "the physical components of a computer", "/ˈhɑrdˌwɛr/", "We upgraded the computer's hardware to run graphic editors faster.", "B2"),
    ("digital", "expressing data as series of the digits 0 and 1", "/ˈdɪdʒɪtəl/", "Digital photography replaced film cameras in the late 1990s.", "B2"),
    ("analog", "relating to signals represented by continuously variable quantities", "/ˈænəˌlɑɡ/", "Some audiophiles prefer the warm sound of analog vinyl records.", "C1"),
    ("broadband", "a high-capacity transmission technique using a wide range of frequencies", "/ˈbrɔrdbænd/", "High-speed broadband allows users to stream high-definition videos.", "B2"),
    ("database", "a structured set of data held in a computer", "/ˈdeɪtəˌbeɪs/", "The library maintains a database of all its cataloged books.", "B2"),
    ("network", "a group or system of interconnected people or things", "/ˈnɛtwərk/", "Social media networks connect users across the globe.", "B2"),
    ("simulation", "the representation of the behavior of one system through another", "/ˌsɪmjʊˈleɪʃən/", "Computers run simulations to predict the path of hurricanes.", "B2"),
    ("virtual", "almost or nearly as described, but not completely; simulated", "/ˈvərtʃuəl/", "The software creates a virtual environment for architect designs.", "B2"),
    ("artificial", "made or produced by human beings rather than occurring naturally", "/ˌɑːrtɪˈfɪʃəl/", "Artificial intelligence can analyze vast amounts of data quickly.", "B2"),
    ("biometrics", "the measurement and analysis of unique physical characteristics", "/ˌbaɪoʊˈmɛtrɪks/", "Fingerprint scanning is a widely used form of biometrics.", "C1"),
    ("cybersecurity", "the state of being protected against the criminal use of electronic data", "/ˌsaɪbərsɪˈkjʊrəti/", "Companies invest in cybersecurity to prevent database hacks.", "B2"),
    ("automation", "the technique of making an apparatus or process control itself", "/ˌɔtəˈmeɪʃən/", "Automation in manufacturing has increased production speeds.", "B2"),
    ("encryption", "conversion of data into a code to prevent unauthorized access", "/ɪnˈkrɪpʃən/", "End-to-end encryption keeps text chats private.", "C1"),
    ("mechanism", "a system of parts working together in a machine", "/ˈmɛkənɪzəm/", "A grandfather clock uses a mechanical pendulum mechanism.", "B2"),

    # --- HISTORY & ARCHAEOLOGY ---
    ("artifact", "an object made by a human being, typically of historical interest", "/ˈɑrtɪfækt/", "Archaeologists discovered clay pots and other ancient artifacts.", "B2"),
    ("chronology", "the arrangement of events or dates in the order of their occurrence", "/krəˈnɑlədʒi/", "The historian established a clear chronology of the war.", "C1"),
    ("civilization", "the stage of human social development and organization", "/ˌsɪvɪlaɪˈzeɪʃən/", "Ancient Mesopotamia is considered the cradle of civilization.", "B2"),
    ("dynasty", "a line of hereditary rulers of a country", "/ˈdɪnəsti/", "The Ming dynasty ruled China for nearly three centuries.", "B2"),
    ("heritage", "valued objects and qualities such as historic buildings and cultural traditions", "/ˈhɛrɪtɪdʒ/", "The historic district is preserved as part of the city's heritage.", "B2"),
    ("excavation", "the action of excavating something, especially an archaeological site", "/ˌɛkskəˈveɪʃən/", "The excavation uncovered ruins of an ancient Roman amphitheater.", "B2"),
    ("fossil", "the remains or impression of a prehistoric organism preserved in petrified form", "/ˈfɑsəl/", "Scientists found a dinosaur fossil embedded in the limestone cliff.", "B2"),
    ("paleontology", "the branch of science concerned with fossil animals and plants", "/ˌpeɪliənˈtɑlədʒi/", "Paleontology helps us understand life on Earth before humans.", "C1"),
    ("medieval", "relating to the Middle Ages", "/ˌmɛdiˈivəl/", "The city has a beautiful medieval castle dating back to 1200.", "B2"),
    ("renaissance", "the revival of art and literature under the influence of classical models", "/ˈrɛnəˌsɑːns/", "Art flourished during the Italian Renaissance in the 15th century.", "B2"),
    ("migration", "movement from one part of something to another", "/maɪˈɡreɪʃən/", "The migration of early humans out of Africa took thousands of years.", "B2"),
    ("colonization", "the action or process of settling among and establishing control over native people", "/ˌkɑːlənəˈzeɪʃən/", "European colonization of the Americas began in the late 1400s.", "B2"),
    ("prehistoric", "relating to the period before written records", "/ˌprihɪsˈtorɪk/", "Cave paintings show scenes of prehistoric animal hunts.", "B2"),
    ("antiquity", "the ancient past, especially the period before the Middle Ages", "/ænˈtɪkwɪti/", "Many Greek statues have survived from classical antiquity.", "C1"),
    ("imperialism", "a policy of extending a country's power through diplomacy or military force", "/ɪmˈpɪriəlˌɪzəm/", "Late 19th-century imperialism led to the partition of Africa.", "C1"),
    ("feudalism", "the dominant social system in medieval Europe", "/ˈfjudəlɪzəm/", "Under feudalism, peasants worked land in exchange for military protection.", "C1"),
    ("nomadic", "living the life of a nomad; wandering", "/noʊˈmædɪk/", "Nomadic tribes moved across the grasslands in search of pasture.", "B2"),
    ("sedentary", "tending to spend much time seated; settled", "/ˈsɛdəntɛri/", "The invention of agriculture led to more sedentary communities.", "B2"),
    ("stratigraphy", "the branch of geology concerned with rock layers and layering", "/strəˈtɪɡrəfi/", "Stratigraphy allows archaeologists to date artifacts based on soil depth.", "C1"),
    ("monarchy", "a form of government with a monarch at the head", "/ˈmɑːnərki/", "The nation transitioned from an absolute monarchy to a democracy.", "B2"),
    ("oligarchy", "a small group of people having control of a country or organization", "/ˈɑːlɪˌɡɑːrki/", "Critics claimed the country was run by a wealthy financial oligarchy.", "C1"),
    ("democracy", "a system of government by the whole population, typically through elected representatives", "/dɪˈmɑːkrəsi/", "Free press is considered a cornerstone of modern democracy.", "B2"),
    ("revolution", "a forcible overthrow of a government or social order", "/ˌrɛvəˈluːʃən/", "The Industrial Revolution transformed agricultural economies.", "B2"),
    ("treaty", "a formally concluded and ratified agreement between countries", "/ˈtriti/", "The two nations signed a peace treaty to end the border dispute.", "B2"),
    ("alliance", "a union or association formed for mutual benefit", "/əˈlaɪəns/", "The military alliance agreed to defend any member under attack.", "B2"),
    ("conflict", "a serious disagreement or argument; a prolonged armed struggle", "/ˈkɑːnflɪkt/", "Historians study the underlying causes of the global conflict.", "B2"),
    ("sovereignty", "supreme power or authority; the authority of a state to govern itself", "/ˈsɑːvrənti/", "The island gained full sovereignty after decades of foreign rule.", "C1"),
    ("agrarian", "relating to cultivated land or the cultivation of land", "/əˈgrɛriən/", "The agrarian society relied heavily on annual wheat harvests.", "C1"),
    ("indigenous", "originating or occurring naturally in a particular place", "/ɪnˈdɪdʒɪnəs/", "Preserving indigenous languages is vital for cultural diversity.", "B2"),
    ("monumental", "great in importance, extent, or size", "/ˌmɑnjʊˈmɛntəl/", "Building the pyramids was a monumental engineering feat.", "B2"),
    ("excavate", "make a hole or channel by digging; reveal by digging", "/ˈɛkskəveɪt/", "Archaeologists planned to excavate the ancient burial mound.", "B2"),
    ("shrine", "a place regarded as holy because of its association with a divinity", "/ʃraɪn/", "Pilgrims traveled from far away to visit the sacred mountain shrine.", "B2"),
    ("treatise", "a written work dealing formally and systematically with a subject", "/ˈtritɪs/", "The philosopher wrote a famous treatise on human ethics.", "C1"),
    ("hierarchy", "a system in which members are ranked according to status", "/ˈhaɪərɑːrki/", "The army has a strict hierarchy where soldiers obey officers.", "B2"),
    ("feudal", "relating to the social system of medieval Europe", "/ˈfjudəl/", "Peasants paid high taxes under the oppressive feudal system.", "C1"),
    ("dynastic", "relating to a line of hereditary rulers", "/daɪˈnæstɪk/", "Dynastic marriages were used to secure political alliances in Europe.", "C1"),
    ("epoch", "a particular period of time in history or a person's life", "/ˈɛpək/", "The fall of the Roman Empire marked the end of an epoch.", "C1"),
    ("precursor", "a person or thing that comes before another of the same kind", "/priˈkɜːrsər/", "The telegraph was the direct precursor of the telephone.", "C1"),
    ("legacy", "an amount of money or property left in a will; a heritage", "/ˈlɛɡəsi/", "The Greek philosophers left a lasting legacy of scientific thought.", "B2"),
    ("preservation", "the act of keeping something valued safe or intact", "/ˌprɛzərˈveɪʃən/", "The historical society is dedicated to the preservation of old photos.", "B2"),

    # --- EDUCATION & PSYCHOLOGY ---
    ("cognition", "the mental action or process of acquiring knowledge and understanding", "/kɑːɡˈnɪʃən/", "Sleep deprivation negatively affects memory and general cognition.", "C1"),
    ("perception", "the ability to see, hear, or become aware of something through the senses", "/pərˈsɛpʃən/", "Our perception of color depends on how our eyes process light waves.", "B2"),
    ("stimulus", "a thing that rouses activity or energy in someone or something", "/ˈstɪmjʊləs/", "The sudden sound of the alarm was a stimulus that woke him up.", "B2"),
    ("conditioning", "the process of training or accustoming a person or animal", "/kənˈdɪʃənɪŋ/", "Classical conditioning can train animals to salivate at a bell sound.", "C1"),
    ("reinforcement", "the process of encouraging or establishing a belief or pattern", "/ˌriɪnˈfɔrsmənt/", "Positive reinforcement, like praise, motivates students to study.", "B2"),
    ("behavioral", "relating to behavior or behavioral science", "/bɪˈheɪvjərəl/", "The school hired a specialist to address behavioral issues in class.", "B2"),
    ("schema", "a representation of a plan or theory in the form of an outline", "/ˈskimə/", "Children develop a schema for animals based on their pets.", "C1"),
    ("aptitude", "a natural ability to do something; suitability", "/ˈæptɪˌtjud/", "The student showed a remarkable aptitude for mathematics.", "B2"),
    ("curriculum", "the subjects comprising a course of study in a school", "/kəˈrɪkjʊləm/", "The school board decided to add computer coding to the curriculum.", "B2"),
    ("pedagogic", "relating to teaching or education", "/ˌpɛdəˈɡɑdʒɪk/", "The teacher experimented with different pedagogic methods.", "C1"),
    ("rote", "mechanical or habitual repetition of something to be learned", "/roʊt/", "Rote memorization is often less effective than conceptual learning.", "B2"),
    ("motivation", "the reason or reasons one has for acting or behaving in a particular way", "/ˈmoʊtɪveɪʃən/", "Financial rewards are not the only motivation for employees.", "B2"),
    ("retention", "the continued possession, use, or control of something; memory", "/rɪˈtɛnʃən/", "Visual aids improve students' retention of historical facts.", "C1"),
    ("assimilation", "the process of absorbing and integrating new information", "/əˌsɪməˈleɪʃən/", "Assimilation of a new culture can take immigrants many years.", "C1"),
    ("accommodation", "a convenient arrangement; adapting schemas to new facts", "/əˌkɑməˈdeɪʃən/", "Piaget defined accommodation as modifying concepts based on new inputs.", "C1"),
    ("bias", "prejudice in favor of or against one thing, person, or group", "/ˈbaɪəs/", "Confirmation bias leads people to ignore contradictory evidence.", "B2"),
    ("heuristics", "mental shortcuts that allow people to solve problems quickly", "/hjuˈrɪstɪks/", "Heuristics help us make rapid decisions under time pressure.", "C1"),
    ("inhibition", "a feeling that makes one self-conscious and unable to act naturally", "/ɪnhɪˈbɪʃən/", "Alcohol can lower social inhibition, making people talkative.", "C1"),
    ("introspection", "the examination of one's own conscious thoughts and feelings", "/ɪntrəˈspɛkʃən/", "Writing in a journal encourages introspection and self-discovery.", "C1"),
    ("temperament", "a person's or animal's nature, especially as it affects behavior", "/ˈtɛmpərəmənt/", "Some dog breeds are known for having a calm, friendly temperament.", "B2"),
    ("cognition", "the process of knowing and processing information", "/kɑːɡˈnɪʃən/", "Cognition involves memory, attention, language, and logic.", "C1"),
    ("empathy", "the ability to understand and share the feelings of another", "/ˈɛmpəθi/", "Active listening is a key way to show empathy in conversations.", "B2"),
    ("sensory", "relating to sensation or the physical senses", "/ˈsɛnsəri/", "The museum offers sensory exhibits designed for touch and smell.", "B2"),
    ("dissonance", "lack of agreement; psychological tension from conflict beliefs", "/ˈdɪsənəns/", "Cognitive dissonance occurs when actions contradict values.", "C1"),
    ("stimuli", "things that arouse activity or energy (plural of stimulus)", "/ˈstɪmjʊˌlaɪ/", "Infants are highly sensitive to visual and auditory stimuli.", "B2"),
    ("instructional", "relating to instruction or teaching", "/ɪnˈstrʌkʃənəl/", "The textbook includes instructional diagrams explaining plant cells.", "B2"),
    ("aptitude", "natural talent or capacity for learning", "/ˈæptɪˌtjud/", "Standardized tests aim to measure general academic aptitude.", "B2"),
    ("curricula", "academic courses of study (plural of curriculum)", "/kəˈrɪkjʊlə/", "Universities update their curricula to match modern job skills.", "C1"),
    ("pedagogy", "the method and practice of teaching", "/ˈpɛdəˌɡɑdʒi/", "Online learning requires a different pedagogy than lecture halls.", "C1"),
    ("retention", "the power of retaining liquid, heat, or knowledge", "/rɪˈtɛnʃən/", "Vocabulary retention is enhanced by using flashcards.", "C1"),

    # --- ECONOMICS & SOCIETY ---
    ("commodity", "a raw material or primary agricultural product that can be bought and sold", "/kəˈmɑdəti/", "Gold, coffee, and crude oil are widely traded commodities.", "B2"),
    ("inflation", "a general increase in prices and fall in the purchasing value of money", "/ɪnˈfleɪʃən/", "High inflation eroded the purchasing power of middle-class families.", "B2"),
    ("recession", "a period of temporary economic decline", "/rɪˈsɛʃən/", "Many businesses closed during the recent global economic recession.", "B2"),
    ("deficit", "the amount by which something, especially a sum of money, is too small", "/ˈdɛfɪsɪt/", "The government took out loans to cover the national budget deficit.", "B2"),
    ("surplus", "an amount of something left over when requirements have been met", "/ˈsərˌplʌs/", "Excellent weather conditions produced a major agricultural surplus.", "B2"),
    ("monopoly", "the exclusive possession or control of the supply of or trade in a commodity", "/məˈnɑpəli/", "The government regulated the utility company to prevent a monopoly.", "B2"),
    ("equilibrium", "a state in which opposing forces or influences are balanced", "/ˌikwɪˈlɪbriəm/", "In economics, market equilibrium occurs where supply meets demand.", "C1"),
    ("fiscal", "relating to government revenue, especially taxes", "/ˈfɪskəl/", "The country implemented a tight fiscal policy to combat inflation.", "C1"),
    ("monetary", "relating to money or currency, especially central bank policy", "/ˈmɑːnəˌtɛri/", "The central bank adjusted monetary policy by raising interest rates.", "C1"),
    ("tariff", "a tax or duty to be paid on a particular class of imports or exports", "/ˈtærɪf/", "The government imposed tariffs on imported steel to protect domestic mills.", "B2"),
    ("globalization", "the process by which businesses operate on an international scale", "/ˌɡloʊbəlaɪˈzeɪʃən/", "Globalization has led to cheaper manufactured goods worldwide.", "B2"),
    ("revenue", "income, especially when of a company or organization", "/ˈrɛvənju/", "The tech company reported a 15 percent increase in annual revenue.", "B2"),
    ("expenditure", "an amount of money spent", "/ɛkˈspɛndɪtʃər/", "The household's largest monthly expenditure was the mortgage payment.", "C1"),
    ("liquidity", "the availability of liquid assets to a market or company", "/lɪkˈwɪdəti/", "The bank maintained high liquidity to handle sudden withdrawals.", "C1"),
    ("capitalism", "an economic system in which a country's trade is controlled by private owners", "/ˈkæpətəlˌɪzəm/", "Capitalism encourages competition and entrepreneurship.", "B2"),
    ("liability", "the state of being responsible for something, especially by law; debts", "/ˌlaɪəˈbɪlɪti/", "The company's liabilities exceeded its assets, leading to bankruptcy.", "C1"),
    ("assets", "property owned by a person or company, regarded as having value", "/ˈæsɛts/", "The investor's assets included stocks, bonds, and real estate.", "B2"),
    ("subsidy", "a sum of money granted by the government to assist an industry", "/ˈsʌbsɪdi/", "Agricultural subsidies help farmers lower the price of milk.", "C1"),
    ("demography", "the study of statistics such as births, deaths, or income", "/dɪˈmɑɡrəfi/", "Demography shifts can predict future housing demands.", "C1"),
    ("stratification", "the arrangement of something into different groups; social classes", "/ˌstrætɪfɪˈkeɪʃən/", "Sociologists study class stratification in urban communities.", "C1"),
    ("urbanization", "the process of making an area more urban", "/ˌərbənɪˈzeɪʃən/", "Industrialization accelerated urbanization in 19th-century Britain.", "B2"),
    ("marginalization", "treatment of a person or group as insignificant", "/ˌmɑːrdʒɪnələˈzeɪʃən/", "High unemployment can lead to the social marginalization of youth.", "C1"),
    ("solidarity", "unity or agreement of feeling or action among individuals", "/ˌsɑlɪˈdærəti/", "Workers organized a strike to show solidarity with fired colleagues.", "C1"),
    ("bureaucracy", "a system of government in which most decisions are made by state officials", "/bjuˈrɑːkrəsi/", "The company simplified its procedures to cut through red tape and bureaucracy.", "C1"),
    ("egalitarian", "believing in the principle that all people are equal", "/ɪˌɡælɪˈtɛriən/", "The utopian community was based on egalitarian principles.", "C1"),
    ("secularization", "the historical process in which religion loses social significance", "/ˈsɛkjələraɪˌzeɪʃən/", "Rapid urbanization is often accompanied by secularization.", "C1"),
    ("pluralism", "a condition in which two or more states or groups coexist", "/ˈplʊrəˌlɪzəm/", "Cultural pluralism enriches the social fabric of the city.", "C1"),
    ("alienation", "the state of being isolated from a group or an activity", "/ˌeɪliəˈneɪʃən/", "The new student felt a sense of alienation during his first week.", "C1"),
    ("liability", "responsibility by law", "/ˌlaɪəˈbɪlɪti/", "Signing the contract limits the business partner's personal liability.", "C1"),
    ("commodity", "marketable item produced to satisfy wants or needs", "/kəˈmɑdəti/", "Wheat is an essential agricultural commodity traded globally.", "B2"),
    ("asset", "a useful or valuable quality, person, or thing", "/ˈæsɪt/", "Fluency in three languages is a major asset in international business.", "B2"),
    ("deficit", "shortage of something, especially money", "/ˈdɛfɪsɪt/", "The school faced a budget deficit and had to cut sports programs.", "B2"),
    ("surplus", "excess of production or supply over demand", "/ˈsərˌplʌs/", "The farmers sold their surplus corn to foreign markets.", "B2"),
    ("monopoly", "exclusive control of a commodity or service in a market", "/məˈnɑpəli/", "Standard Oil held a virtual monopoly over the oil industry.", "B2"),
    ("fiscal", "relating to financial matters", "/ˈfɪskəl/", "The government declared a new fiscal package to boost employment.", "C1"),
    ("monetary", "relating to coins or currency", "/ˈmɑːnəˌtɛri/", "The country's monetary unit is the dollar.", "C1"),
    ("globalization", "spread of products, technology, and jobs across borders", "/ˌɡloʊbəlaɪˈzeɪʃən/", "Globalization allowed companies to source cheaper raw materials.", "B2"),
    ("urbanization", "movement of populations from rural to urban areas", "/ˌərbənɪˈzeɪʃən/", "Rapid urbanization can put a strain on city water networks.", "B2"),
    ("demographics", "statistical data relating to the population", "/ˌdɛməˈɡræfɪks/", "The demographics of the city are shifting as younger families move in.", "B2"),
    ("stratification", "classification of people into groups based on socio-economic status", "/ˌstrætɪfɪˈkeɪʃən/", "Social stratification can limit upward economic mobility.", "C1"),
    
    # --- MORE MIXED ACADEMIC WORDS ---
    ("acknowledge", "accept or admit the existence or truth of", "/əkˈnɑlɪdʒ/", "The author acknowledged the assistance of her research partner.", "B2"),
    ("compile", "produce by assembling information collected from other sources", "/kənˈpaɪl/", "The researcher compiled data from dozens of different studies.", "B2"),
    ("concede", "admit that something is true or valid after first denying it", "/kənˈsid/", "The candidate conceded defeat after the votes were counted.", "C1"),
    ("contradict", "deny the truth of a statement by asserting the opposite", "/ˌkɑːntrəˈdɪkt/", "The new evidence directly contradicts the previous theory.", "B2"),
    ("depict", "show or represent by a drawing, painting, or other art form", "/dɪˈpɪkt/", "The painting depicts a busy harbor during the 18th century.", "B2"),
    ("deviate", "depart from an established course or standards", "/ˈdiviət/", "The flight had to deviate from its route to avoid the storm.", "C1"),
    ("distort", "pull or twist out of shape; give a misleading account of", "/dɪsˈtɔrt/", "Some media channels distort the facts to create a sensational story.", "B2"),
    ("evaluate", "form an idea of the amount, number, or value of; assess", "/ɪˈvæljʊeɪt/", "Teachers evaluate student progress using tests and essays.", "B2"),
    ("inhibit", "hinder, restrain, or prevent an action or process", "/ɪnˈhɪbɪt/", "Low temperatures inhibit the growth of most bacteria.", "C1"),
    ("integrate", "combine one thing with another so that they become a whole", "/ˈɪntəɡreɪt/", "The immigrant family worked hard to integrate into their new neighborhood.", "B2"),
    ("manipulate", "handle or control, typically in a skillful manner", "/məˈnɪpjʊleɪt/", "The technician manipulated the robot arm using a controller.", "B2"),
    ("modify", "make partial or minor changes to something", "/ˈmɑdɪfaɪ/", "The engineer modified the design to make it more wind-resistant.", "B2"),
    ("offset", "counterbalance, counteract, or compensate for", "/ɑfˈsɛt/", "The company planted trees to offset its carbon emissions.", "C1"),
    ("persist", "continue firmly in an opinion or a course of action", "/pəˈsɪst/", "If the symptoms persist, you should consult a doctor.", "B2"),
    ("precede", "come before something in time, order, or position", "/priˈsid/", "A light breeze often precedes a severe thunderstorm.", "B2"),
    ("reject", "dismiss as inadequate, unacceptable, or faulty", "/rɪˈdʒɛkt/", "The journal rejected the article due to flawed research methodology.", "B2"),
    ("restore", "bring back a previous right, practice, custom, or situation", "/rɪˈstɔr/", "The government aims to restore public trust in the judicial system.", "B2"),
    ("supplement", "add an extra element or amount to", "/ˈsʌpləmənt/", "Students can supplement their classes with online tutorials.", "B2"),
    ("transform", "make a thorough or dramatic change in the form or character", "/trænzˈfɔrm/", "The internet has transformed the way people shop and work.", "B2"),
    ("trigger", "cause an event or situation to happen or exist", "/ˈtrɪɡər/", "Loud noises can trigger an avalanche in snowy mountains.", "B2"),
    ("accumulate", "gather or build up a scale of something over time", "/əˈkjumjʊˌleɪt/", "Dust can accumulate quickly in unoccupied rooms.", "B2"),
    ("advocate", "person who publicly supports a cause or policy", "/ˈædvəkeɪt/", "He is a strong advocate for animal welfare legislation.", "C1"),
    ("bias", "systematic distortion of statistical or cognitive processes", "/ˈbaɪəs/", "A random sampling method helps eliminate selection bias in studies.", "B2"),
    ("cohere", "be logically consistent or unified", "/koʊˈhɪr/", "The chapters of the novel cohere into a unified theme.", "C1"),
    ("compound", "a thing that is composed of two or more separate elements", "/ˈkɑːmpaʊnd/", "Water is a chemical compound of hydrogen and oxygen.", "B2"),
    ("confine", "keep or restrict someone or something within certain limits", "/kənˈfaɪn/", "The floodwaters were confined to the agricultural valley.", "B2"),
    ("consent", "permission for something to happen or agreement to do something", "/kənˈsɛnt/", "Participants gave their written consent to join the study.", "B2"),
    ("constitute", "be a part of a whole; establish", "/ˈkɑːnstəˌtuːt/", "Single parents constitute a growing percentage of households.", "B2"),
    ("constrain", "severely restrict the scope, activity, or execution of", "/kənˈstreɪn/", "High energy costs constrain the growth of local industries.", "C1"),
    ("contradict", "be in conflict with", "/ˌkɑːntrəˈdɪkt/", "The two witnesses gave statements that contradict each other.", "B2"),
    ("controversy", "disagreement, typically when prolonged, public, and heated", "/ˈkɑːntrəˌvərsi/", "The construction of the new highway sparked intense controversy.", "B2"),
    ("empirical", "derived from experiment and observation rather than theory", "/ɛmˈpɪrɪkəl/", "Her thesis is based on empirical research of consumer habits.", "C1"),
    ("equivalent", "equal in value, amount, function, meaning, etc.", "/ɪˈkwɪvələnt/", "One mile is equivalent to approximately 1.6 kilometers.", "B2"),
    ("fluctuate", "rise and fall irregularly in number or amount", "/ˈflʌktʃuˌeɪt/", "Vegetable prices fluctuate depending on the season and weather.", "B2"),
    ("hypothesis", "tentative explanation that can be tested by further research", "/haɪˈpɑːθəsɪs/", "Scientists ran experiments to test their hypothesis.", "C1"),
    ("implicit", "implied though not plainly expressed", "/ɪmˈplɪsɪt/", "There was an implicit agreement that the project would remain secret.", "C1"),
    ("induce", "succeed in persuading or influencing someone to do something", "/ɪnˈduːs/", "The doctor administered medication to induce sleep.", "C1"),
    ("inevitable", "certain to happen; unavoidable", "/ɪnˈɛvɪtəbəl/", "As technology advances, some job roles will inevitably change.", "B2"),
    ("inherent", "existing in something as a permanent, essential, or characteristic attribute", "/ɪnˈhɪrənt/", "Every investment carries an inherent level of financial risk.", "C1"),
    ("intensity", "the quality of being intense; strength or concentration", "/ɪnˈtɛnsəti/", "The storm increased in intensity as it approached the coast.", "B2"),
    ("logic", "reasoning conducted according to strict principles of validity", "/ˈlɑːdʒɪk/", "Her argument was clear and followed a strict academic logic.", "B2"),
    ("margin", "the edge or border of something; amount by which something is won", "/ˈmɑːrdʒɪn/", "The team won the championship match by a very narrow margin.", "B2"),
    ("neutral", "not supporting or helping either side in a conflict", "/ˈnuːtrəl/", "Switzerland remained neutral during both world wars.", "B2"),
    ("nuclear", "relating to a nucleus, atomic energy, or nuclear weapons", "/ˈnuːkliər/", "The country built nuclear power plants to reduce coal use.", "B2"),
    ("passive", "accepting or allowing what happens or what others do", "/ˈpæsɪv/", "Watching television is generally a passive form of entertainment.", "B2"),
    ("practitioner", "a person actively engaged in an art, discipline, or profession", "/prækˈtɪʃənər/", "She is an experienced practitioner of family medicine.", "C1"),
    ("qualitative", "relating to, measuring, or measured by the quality of something", "/ˈkwɑːlɪˌteɪtɪv/", "The survey collected qualitative feedback on customer service.", "C1"),
    ("ratio", "the quantitative relation between two amounts showing their relative size", "/ˈreɪʃioʊ/", "The teacher-student ratio at the school is 1 to 15.", "B2"),
    ("refine", "make minor changes so as to improve something; clarify", "/rɪˈfaɪn/", "The author spent weeks refining the plot of the novel.", "B2"),
    ("rigid", "unable to bend or be forced out of shape; not adaptable", "/ˈrɪdʒɪd/", "The company's rigid hierarchy made fast decisions difficult.", "C1"),
    ("scenario", "a written outline of a movie, novel, or stage work; situation", "/səˈnɛrioʊ/", "Economists analyzed the worst-case scenario for the stock market.", "B2"),
    ("sphere", "a round solid figure; an area of activity, interest, or expertise", "/sfɪr/", "The country sought to expand its sphere of political influence.", "B2"),
    ("subordinate", "lower in rank or position", "/səˈbɔːrdənət/", "A manager oversees the work of all subordinate employees.", "C1"),
    ("temporary", "lasting for only a limited period of time; not permanent", "/ˈtɛmpəˌrɛri/", "The library was closed for temporary repairs to the roof.", "B2"),
    ("uniform", "not changing in form or character; remaining the same in all cases", "/ˈjunəˌfɔːrm/", "The bricks were laid out in a neat, uniform pattern.", "B2"),
    ("valid", "having a sound basis in logic or fact; reasonable or cogent", "/ˈvælɪd/", "You raise a valid point that deserves further discussion.", "B2"),
    ("abstract", "existing in thought or as an idea but not having a physical existence", "/ˈæbstrækt/", "Mathematics deals with abstract concepts rather than physical things.", "B2"),
    ("accurate", "correct in all details; exact", "/ˈækjərət/", "The weather forecast proved to be highly accurate.", "B2"),
    ("brief", "of short duration; concise", "/brif/", "The speaker gave a brief introduction before the presentation.", "B2"),
    ("capable", "having the ability, fitness, or quality necessary to do something", "/ˈkeɪpəbəl/", "She is a highly capable engineer who can handle complex projects.", "B2"),
    ("displace", "take the place of; force to leave home", "/dɪsˈpleɪs/", "Coal is being displaced by natural gas and renewable energy.", "B2"),
    ("diversity", "the state of being diverse; variety", "/daɪˈvərsəti/", "Cultural diversity enriched the neighborhood's restaurants.", "B2"),
    ("exceed", "be greater in number or size than; go beyond limits", "/ɪkˈsid/", "The final cost of the project exceeded the initial budget.", "B2"),
    ("exhibit", "publicly display; manifest clearly", "/ɪɡˈzɪbɪt/", "The museum is exhibiting a collection of ancient Egyptian pottery.", "B2"),
    ("federal", "relating to a system of government with central and state division", "/ˈfɛdərəl/", "The federal government regulates interstate commerce.", "B2"),
    ("furthermore", "in addition; besides", "/ˌfərdərˈmɔːr/", "The house is beautiful; furthermore, it is close to the school.", "B2"),
    ("ignorant", "lacking knowledge or awareness in general", "/ˈɪɡnərənt/", "Many people were ignorant of the new law's tax implications.", "B2"),
    ("incentive", "a thing that motivates or encourages one to do something", "/ɪnˈsɛntɪv/", "Tax breaks provide an incentive for companies to go green.", "B2"),
    ("lecture", "an educational talk to an audience, especially to students", "/ˈlɛktʃər/", "The professor gave an interesting lecture on organic chemistry.", "B2"),
    ("maximum", "as great, high, or intense as possible", "/ˈmæksəməm/", "The highway has a maximum speed limit of 70 miles per hour.", "B2"),
    ("minimize", "reduce to the smallest possible amount or degree", "/ˈmɪnəˌmaɪz/", "Seatbelts are designed to minimize the risk of injury in a crash.", "B2"),
    ("nevertheless", "in spite of that; notwithstanding; all the same", "/ˌnɛvərðəˈlɛs/", "The path was steep; nevertheless, they reached the summit.", "B2"),
    ("precise", "marked by exactness and accuracy of detail", "/prɪˈsaɪs/", "The scientist took precise measurements of the temperature.", "B2"),
    ("radical", "relating to or affecting the fundamental nature of something", "/ˈrædɪkəl/", "The company underwent a radical restructuring to save costs.", "C1"),
    ("reveal", "make known to others; allow to be seen", "/rɪˈvil/", "The research revealed that the virus could survive on metal.", "B2"),
    ("scope", "the extent of the area or subject matter that something deals with", "/skoʊp/", "The study fell outside the scope of the committee's research.", "B2"),
    ("underlying", "significant as a cause or basis of something but not obvious", "/ˌʌndərˈlaɪɪŋ/", "High stress was the underlying cause of his sleep issues.", "C1"),
    ("widespread", "found or distributed over a large area or number of people", "/ˈwaɪdˌsprɛd/", "The storm caused widespread power outages across the state.", "B2"),
    ("advocate", "recommend; speak in favor of", "/ˈædvəkeɪt/", "Environmentalists advocate for cleaner air regulations.", "C1"),
    ("bias", "influence in an unfair way", "/ˈbaɪəs/", "The researcher's opinions should not bias the test results.", "B2"),
    ("compile", "get or gather together", "/kənˈpaɪl/", "It took months to compile the statistics for the report.", "B2"),
    ("complement", "make complete or perfect", "/ˈkɑːmpləmənt/", "A side salad is a perfect complement to the main course.", "B2"),
    ("cooperate", "work together on a common project", "/koʊˈɑːpəˌreɪt/", "Local police cooperated with federal agents to solve the case.", "B2"),
    ("deviate", "turn aside; turn away from", "/ˈdiviət/", "The scientist had to deviate from the standard test guidelines.", "C1"),
    ("empirical", "relying on medical or scientific practical experience", "/ɛmˈpɪrɪkəl/", "Modern medicine relies heavily on empirical clinical trials.", "C1"),
    ("framework", "a basic structure underlying a system, concept, or text", "/ˈfreɪmˌwərk/", "The constitution provides the legal framework for the country.", "B2"),
    ("hypothesize", "put forward as a hypothesis", "/haɪˈpɑːθəˌsaɪz/", "The geologists hypothesized that the lake was formed by a meteor.", "C1"),
    ("inhibit", "limit the range or extent of", "/ɪnˈhɪbɪt/", "Fears of failure can inhibit students from trying new skills.", "C1"),
    ("justify", "show or prove to be right or reasonable", "/ˈdʒʌstəˌfaɪ/", "The director justified the budget increase by showing rising costs.", "B2"),
    ("offset", "compensate for", "/ɑfˈsɛt/", "Gains in efficiency can offset the cost of upgrading machinery.", "C1"),
    ("precede", "move before in time or space", "/priˈsid/", "Dark clouds precede the arrival of a summer storm.", "B2"),
    ("primary", "of first rank or importance or value", "/ˈpraɪˌmɛri/", "The primary goal of the program is to teach basic reading.", "B2"),
    ("radical", "far-reaching; revolutionary", "/ˈrædɪkəl/", "Introducing computers was a radical change in the classroom.", "C1"),
    ("revenue", "government income due to taxation", "/ˈrɛvənju/", "Income taxes are the primary source of federal revenue.", "B2"),
    ("terminate", "bring to an end or halt", "/ˈtərməˌneɪt/", "The landlord decided to terminate the lease agreement.", "B2"),
    ("ultimate", "furthest or highest in degree or order", "/ˈʌltəmət/", "The ultimate source of energy for the earth is the sun.", "B2"),
    ("undergo", "pass through", "/ˌʌndərˈɡoʊ/", "The building must undergo inspections before opening.", "B2"),
    ("virtually", "almost completely", "/ˈvərtʃuəli/", "The virus had virtually disappeared from the local population.", "B2"),
    ("validate", "prove or declare to be logically valid or correct", "/ˈvælɪdeɪt/", "The lab results validated the researcher's theory.", "B2"),
    ("conjecture", "an opinion or conclusion formed on the basis of incomplete information", "/kənˈdʒɛktʃər/", "Her theory is pure conjecture with no real proof.", "C1"),
    ("delineate", "describe or portray something precisely", "/dɪˈlɪniˌeɪt/", "The contract clearly delineates the roles of each partner.", "C1"),
    ("substantiate", "provide evidence to support or prove the truth of", "/səbˈstænʃiˌeɪt/", "We need more data to substantiate these claims.", "C1"),
    ("transient", "lasting only for a short time; impermanent", "/ˈtrænʃənt/", "The symptoms were transient and disappeared in a few hours.", "C1"),
    ("ubiquitous", "present, appearing, or found everywhere", "/juˈbɪkwətəs/", "Mobile phones are now ubiquitous in modern society.", "B2"),
    ("anomaly", "something that deviates from what is standard, normal, or expected", "/əˈnɑməli/", "The sudden temperature spike was a seasonal anomaly.", "C1"),
    ("cognitive", "relating to cognition or the process of acquiring knowledge", "/ˈkɑɡnətɪv/", "Reading books stimulates children's cognitive development.", "B2"),
    ("discrepancy", "an illogical lack of compatibility or similarity between two or more facts", "/dɪˈskrɛpənsi/", "There was a discrepancy between the two bank reports.", "C1"),
    ("fluctuation", "an irregular rising and falling in number or amount", "/ˌflʌktʃuˈeɪʃən/", "Market fluctuations affect commodity prices daily.", "B2"),
    ("scrutinize", "examine or inspect closely and thoroughly", "/ˈskrutəˌnaɪz/", "The lawyers will scrutinize every word of the agreement.", "C1"),
    ("adversary", "one's opponent in a contest, conflict, or dispute", "/ˈædvərˌsɛri/", "She defeated her adversary in the final round of debate.", "B2"),
    ("aesthetic", "concerned with beauty or the appreciation of beauty", "/ɛsˈθɛtɪk/", "The building design has a modern and clean aesthetic.", "B2"),
    ("benevolent", "well meaning and kindly; charitable", "/bəˈnɛvələnt/", "The school received a large donation from a benevolent donor.", "B2"),
    ("capricious", "given to sudden and unaccountable changes of mood or behavior", "/kəˈprɪʃəs/", "The weather here is capricious, shifting from sun to rain in minutes.", "C1"),
    ("corroborate", "confirm or give support to a statement or theory", "/kəˈrɑrbəˌreɪt/", "Three witnesses corroborated the suspect's alibi.", "C1"),
    ("deference", "humble submission and respect", "/ˈdɛfərəns/", "The young soldier showed deference to his commanding officer.", "C1"),
    ("diligent", "having or showing care and conscientiousness in one's work", "/ˈdɪlɪdʒənt/", "She is a diligent student who always completes her homework.", "B2"),
    ("disparate", "essentially different in kind; not allowing comparison", "/ˈdɪspərət/", "The team was made up of individuals from disparate backgrounds.", "C1"),
    ("elusive", "difficult to find, catch, or achieve", "/ɪˈlusɪv/", "Success remained elusive despite years of hard work.", "B2"),
    ("ephemeral", "lasting for a very short time", "/ɪˈfɛmərəl/", "Fame in the social media era is often ephemeral.", "C1"),
    ("exacerbate", "make a problem or bad situation worse", "/ɪɡˈzæsərˌbeɪt/", "Running on a sprained ankle will exacerbate the injury.", "C1"),
    ("pragmatic", "dealing with things sensibly and realistically in a practical way", "/præɡˈmætɪk/", "We need a pragmatic solution rather than a theoretical one.", "B2"),
    ("redundant", "no longer needed or useful; superfluous", "/rɪˈdʌndənt/", "The backup power generator made the second battery redundant.", "B2"),
    ("tenacious", "tending to keep a firm hold of something; persistent", "/təˈneɪʃəs/", "The attorney was a tenacious defender of civil rights.", "C1")
]

# Shuffle or slice to get exactly 280 new words, then verify duplicates.
new_words_list = []
seen_words = set(w["word"].lower() for w in EXISTING_WORDS)

# Generate vocabulary dictionaries
id_counter = len(EXISTING_WORDS) + 1  # starts from 21 (vocab_021)
for item in NEW_WORDS_RAW:
    word, translation, transcription, example, level = item
    word_lower = word.lower()
    if word_lower in seen_words:
        continue
    seen_words.add(word_lower)
    
    vocab_id = f"vocab_{id_counter:03d}"
    new_words_list.append({
        "id": vocab_id,
        "word": word,
        "translation": translation,
        "transcription": transcription,
        "example": example,
        "level": level
    })
    id_counter += 1

# Ensure we have exactly 330 new words to reach 350 total
total_required = 350
new_needed = total_required - len(EXISTING_WORDS)
if len(new_words_list) < new_needed:
    raise ValueError(f"Only generated {len(new_words_list)} unique words, but need {new_needed}.")

# Slice exactly the amount we need
final_new_words = new_words_list[:new_needed]
all_words = EXISTING_WORDS + final_new_words

# Double check that we have exactly 350 words
print(f"Total vocabulary size: {len(all_words)}")
assert len(all_words) == 350, f"Expected 350 words, got {len(all_words)}"

# Write to data/vocabulary.json
vocab_file = Path("data/vocabulary.json")
with vocab_file.open("w", encoding="utf-8") as f:
    json.dump(all_words, f, indent=2, ensure_ascii=False)

print("Successfully wrote 350 TOEFL words to data/vocabulary.json")

# Validate with JsonContentLoader
async def validate():
    loader = JsonContentLoader()
    words = await loader.load_vocabulary()
    print(f"Validation: Loaded {len(words)} words using JsonContentLoader.")
    assert len(words) == 350, "Validation failed: Loaded size is not 350"
    print("Validation successful!")

asyncio.run(validate())
